const safeexplorer = {
  CHAIN: 'https://chain.safeexplorer.io',
  OOT: 'https://oot.safeexplorer.io',
  ETOMIC: 'https://etomic.safeexplorer.io',
  BEER: 'https://beer.safeexplorer.io',
  BTCH: 'https://btch.safeexplorer.io',
  COQUI: 'https://coqui.safeexplorer.io',
  BET: 'https://bet.safeexplorer.io',
  BOTS: 'https://bot.safeexplorer.io',
  CEAL: 'https://ceal.safeexplorer.io',
  CRYPTO: 'https://crypto.safeexplorer.io',
  DEX: 'https://dex.safeexplorer.io',
  HODL: 'https://hodl.safeexplorer.io',
  JUMBLR: 'https://jumblr.safeexplorer.io',
  KV: 'https://kv.safeexplorer.io',
  MESH: 'https://mesh.safeexplorer.io',
  MGW: 'https://mgw.safeexplorer.io',
  MSHARK: 'https://mshark.safeexplorer.io',
  MVP: 'https://mvp.safeexplorer.io',
  PANGEA: 'https://pangea.safeexplorer.io',
  PIZZA: 'https://pizza.safeexplorer.io',
  REVS: 'https://revs.safeexplorer.io',
  SUPERNET: 'https://supernet.safeexplorer.io',
  SHARK: 'https://shark.safeexplorer.io',
  WLC: 'https://wlc.safeexplorer.io',
  AXO: 'https://axo.safeexplorer.io',
  DSEC: 'https://dsec.safeexplorer.io',
  NINJA: 'https://ninja.safeexplorer.io',
  GLXT: 'https://glxt.safeexplorer.io',
  PRLPAY: 'https://prlpay.safeexplorer.io',
  BNTN: 'https://bntn.safeexplorer.io',
  EQL: 'https://eql.safeexplorer.io',
  VRSC: 'https://vrsc.safeexplorer.io',
  ZILLA: 'https://zilla.safeexplorer.io',
  MGNX: 'http://mgnx.explorer.dexstats.info',
  CALL: 'https://call.explorer.mycapitalco.in',
  CCL: 'https://ccl.safeexplorer.io',
  PIRATE: 'https://pirate.safeexplorer.io',
  DION: 'https://explorer.dionpay.com',
};

export default safeexplorer;